export const REQUEST_PLANETS = 'REQUEST_PLANETS';
export const RECEIVE_PLANETS = 'RECEIVE_PLANETS';
export const REQUEST_SPACESHPIS = 'REQUEST_SPACESHPIS';
export const RECEIVE_SPACESHPIS = 'RECEIVE_SPACESHPIS';
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE';
export const RECEIVE_PEOPLE = 'RECEIVE_PEOPLE';
